---
#
# Ansible managed
#
repository:
  description: Install and configure gitea on your system.
  homepage: https://buluma.github.io/
  topics: gitea, ansible, molecule, tox, playbook, hacktoberfest
