---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Run gitea --version
      ansible.builtin.command:
        cmd: gitea --version

    - name: Check port 3000
      ansible.builtin.wait_for:
        port: 3000
